In [17]:
import os
import requests
import pandas as pd

from dotenv import load_dotenv

load_dotenv()

google_maps_key = os.getenv("GOOGLE_MAPS_API_KEY")

print("API key configured:", google_maps_key is not None)

API key configured: True

In [18]:
url = "https://places.googleapis.com/v1/places:searchText"

headers = {
    "Content-Type": "application/json",
    "X-Goog-Api-Key": google_maps_key,
    "X-Goog-FieldMask": (
        "places.id,"
        "places.displayName,"
        "places.formattedAddress,"
        "places.rating,"
        "places.userRatingCount,"
        "places.priceLevel,"
        "places.types,"
        "places.location"
    )
}

payload = {
    "textQuery": "cafes in Whitefield, Bangalore",
    "pageSize": 20
}

response = requests.post(
    url,
    headers=headers,
    json=payload
)

print("Status code:", response.status_code)
print(response.text[:2000])

Status code: 200
{
  "places": [
    {
      "id": "ChIJX04baGgTrjsRw4WgBajPHwM",
      "types": [
        "restaurant",
        "garden",
        "coffee_shop",
        "parking_lot",
        "cafe",
        "bakery",
        "parking",
        "farm",
        "food_store",
        "transportation_service",
        "store",
        "food",
        "point_of_interest",
        "service",
        "establishment"
      ],
      "formattedAddress": "Lake View Farm, Main Road, Whitefield Main Rd, Varthur, Palm Meadows, Siddapura, Whitefield, Bengaluru, Karnataka 560066, India",
      "location": {
        "latitude": 12.956800699999999,
        "longitude": 77.732992299999992
      },
      "rating": 4.2,
      "priceLevel": "PRICE_LEVEL_MODERATE",
      "userRatingCount": 1439,
      "displayName": {
        "text": "Farmhouse Kitchen & Bakery",
        "languageCode": "en"
      }
    },
    {
      "id": "ChIJ1xBDVxkPrjsRs547ztuQkro",
      "types": [
        "cafe",
        "restaurant",
        "food",
        "point_of_interest",
        "establishment"
      ],
      "formattedAddress": "Ground Floor, Block B, Garden of Eden by UKN, B 002, Pattandur Agrahara Vishnuvardhan Rd, Whitefield, Bengaluru, Karnataka 560066, India",
      "location": {
        "latitude": 12.980362399999999,
        "longitude": 77.7506274
      },
      "rating": 4.7,
      "priceLevel": "PRICE_LEVEL_MODERATE",
      "userRatingCount": 251,
      "displayName": {
        "text": "ChayaChyll",
        "languageCode": "en"
      }
    },
    {
      "id": "ChIJuzM6WDkTrjsRduv5wYDLE1I",
      "types": [
        "cafe",
        "food",
        "point_of_interest",
        "establishment"
      ],
      "formattedAddress": "66/2, 2nd Main Rd, Nallurhalli, Whitefield, Bengaluru, Karnataka 560066, India",
      "location": {
        "latitude": 12.965383200000002,
        "longitude": 77.7324064
      },
      "rating": 4.3,
      "priceLevel": "PRICE_LEVEL_MODERATE",
      "userRatingCount": 1153,
      "displ

In [19]:
data = response.json()

places = data.get("places", [])

print("Places returned:", len(places))

Places returned: 20

In [20]:
rows = []

for place in places:
    rows.append({
        "place_id": place.get("id"),
        "name": place.get("displayName", {}).get("text"),
        "address": place.get("formattedAddress"),
        "rating": place.get("rating"),
        "review_count": place.get("userRatingCount"),
        "price_level": place.get("priceLevel"),
        "types": place.get("types"),
        "latitude": place.get("location", {}).get("latitude"),
        "longitude": place.get("location", {}).get("longitude")
    })

places_df = pd.DataFrame(rows)

print("Shape:", places_df.shape)
print("Columns:", places_df.columns.tolist())

display(places_df)

Shape: (20, 9)
Columns: ['place_id', 'name', 'address', 'rating', 'review_count', 'price_level', 'types', 'latitude', 'longitude']

,place_id,name,address,rating,review_count,price_level,types,latitude,longitude
0,ChIJX04baGgTrjsRw4WgBajPHwM,Farmhouse Kitchen & Bakery,"Lake View Farm, Main Road, Whitefield Main Rd,...",4.2,1439,PRICE_LEVEL_MODERATE,"[restaurant, garden, coffee_shop, parking_lot,...",12.956801,77.732992
1,ChIJ1xBDVxkPrjsRs547ztuQkro,ChayaChyll,"Ground Floor, Block B, Garden of Eden by UKN, ...",4.7,251,PRICE_LEVEL_MODERATE,"[cafe, restaurant, food, point_of_interest, es...",12.980362,77.750627
2,ChIJuzM6WDkTrjsRduv5wYDLE1I,Paper & Pie,"66/2, 2nd Main Rd, Nallurhalli, Whitefield, Be...",4.3,1153,PRICE_LEVEL_MODERATE,"[cafe, food, point_of_interest, establishment]",12.965383,77.732406
3,ChIJA2t-vlMPrjsRmjCRWcdBDmk,Café Fiori - Dining,"B104, Garden of Eden, attandur Agrahara Kalida...",4.8,230,PRICE_LEVEL_MODERATE,"[cafe, coffee_shop, european_restaurant, food_...",12.980370,77.750804
4,ChIJFSN05AoTrjsR0PTHn-vlsXo,Blue Tokai Coffee Roasters | Divyashree Republ...,"23, Kundalahalli Road, Brookefield, Whitefield...",4.3,61,PRICE_LEVEL_MODERATE,"[coffee_shop, coffee_roastery, cafe, food_stor...",12.970831,77.725541
5,ChIJAwl7EnoRrjsR62wk66pFEH4,Hard Rock Cafe Whitefield,"40, ITPL Main Rd Unit no.G, Ground Floor, 25 &...",4.5,6183,NaN,"[american_restaurant, cafe, pub, bar, restaura...",12.987126,77.736481
6,ChIJqbYZ09ERrjsRa_v6WlJiZSQ,Beanlore Coffee Roasters - Whitefield,"No. 2, behind HDFC Bank, Hoodi, Doddanakundi I...",4.3,84,PRICE_LEVEL_EXPENSIVE,"[coffee_shop, cafe, food_store, store, food, p...",12.982164,77.709021
7,ChIJL5dKDgARrjsR8d6sSxyUZZo,Cafe Levista,"Opp SJR I PARK, Sri Sathya Sai Metro Station, ...",4.5,93,PRICE_LEVEL_INEXPENSIVE,"[coffee_shop, cafe, food_store, store, food, p...",12.981570,77.727507
8,ChIJ17yVZgATrjsRSfpCP6QAu2Q,Grill Sip Café,"Pavani Sarovar, Lake, Pattandur Agrahara Villa...",4.8,20,PRICE_LEVEL_INEXPENSIVE,"[coffee_shop, cafe, food_store, store, food, p...",12.972566,77.734353
9,ChIJI1FePhwTrjsRnaemUnbrG18,Lake view cafe,"apartment lake, Nallurahalli Main Rd, near Pho...",4.7,79,PRICE_LEVEL_INEXPENSIVE,"[cafe, food, point_of_interest, establishment]",12.972520,77.734314
10,ChIJRfPzhy0TrjsRY8LkS2vFJBw,One 9 Popina,"GROUND FLOOR, Brigade Irv Center, G-03A, Popin...",4.8,101,PRICE_LEVEL_MODERATE,"[cafe, coffee_shop, pizza_restaurant, food_sto...",12.970189,77.730570
11,ChIJD1Lm-wMOrjsRNy3uzc792_c,The Ants Store and cafe,"#5, Avalon, 1st Main Road, Whitefield Main Rd,...",3.9,644,PRICE_LEVEL_MODERATE,"[cafe, coffee_shop, food_store, store, restaur...",12.980680,77.751155
12,ChIJsykr5KURrjsREIFoN2nXXpg,Lavonne Café,"004, Lower Ground Floor, Forum Mall Whitefield...",4.4,316,PRICE_LEVEL_MODERATE,"[cafe, food, point_of_interest, establishment]",12.989646,77.727800
13,ChIJxTQDVAUTrjsRfnR-Q8jVmlI,Bake Stir Fry Cafe,"Shop#2, 56/6, Borewell Rd, near Victorian View...",4.6,365,PRICE_LEVEL_MODERATE,"[cafe, breakfast_restaurant, coffee_shop, food...",12.969021,77.737813
14,ChIJk81jowsRrjsROM_gH-kYYrw,Issimo Cafe,"Primeco Union City, ITPL Main Rd, Sadara Manga...",4.5,68,PRICE_LEVEL_MODERATE,"[cafe, food, point_of_interest, establishment]",12.989591,77.732616
15,ChIJ3RUzPPkTrjsRQXhWIiYQpN8,Kink coffee Whitefield,"109, Gateway Park, off Nallurahalli Main Road,...",4.5,20,PRICE_LEVEL_MODERATE,"[coffee_shop, cafe, food_store, store, food, p...",12.962873,77.732398
16,ChIJn8ULh78PrjsRqxeoKJP3AWE,SMOOR Lounge - Whitefield,"64, SH 35, Phase 2, Narayanappa Garden, Whitef...",4.4,1567,NaN,"[bakery, dessert_shop, confectionery, food_sto...",12.965780,77.749265
17,ChIJ5ZEg0jMTrjsR7MT3Yd2b63c,Third Wave Coffee,"Plot No 207, Varthur Main Rd, Palm Meadows, Ra...",4.5,1001,PRICE_LEVEL_MODERATE,"[cafe, coffee_shop, coffee_roastery, food_stor...",12.957298,77.736776
18,ChIJFUJWwXYTrjsR7cYWErDdiAg,The Whitefield Cafe,"Shop No. 4, Sy. No. 66/8, Nallurahalli Main Rd...",4.6,9,PRICE_LEVEL_INEXPENSIVE,"[restaurant, food, point_of_interest, establis...",12.965708,77.733348
19,ChIJA6ofa_kNrjsRYdD-Xd7yne8,Glen's Bakehouse Whitefield,"7A, Whitefield Main Rd, Narayanappa Garden, Wh...",4.2,12528,PRICE_LEVEL_MODERATE,"[bakery, breakfast_restaurant, pizza_restauran...",12.967270,77.749805

In [21]:
places_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   place_id      20 non-null     str
 1   name          20 non-null     str
 2   address       20 non-null     str
 3   rating        20 non-null     float64
 4   review_count  20 non-null     int64
 5   price_level   18 non-null     str
 6   types         20 non-null     object
 7   latitude      20 non-null     float64
 8   longitude     20 non-null     float64
dtypes: float64(3), int64(1), object(1), str(4)
memory usage: 1.5+ KB

In [22]:
print("Duplicate place IDs:", places_df["place_id"].duplicated().sum())

print("\nMissing values:")
print(places_df.isnull().sum())

Duplicate place IDs: 0

Missing values:
place_id        0
name            0
address         0
rating          0
review_count    0
price_level     2
types           0
latitude        0
longitude       0
dtype: int64

In [23]:
target_lat = 12.9698
target_lon = 77.7499

print("Target latitude:", target_lat)
print("Target longitude:", target_lon)

Target latitude: 12.9698
Target longitude: 77.7499

In [24]:
import numpy as np

def haversine_distance(lat1, lon1, lat2, lon2):
    R = 6371  # Earth radius in km

    lat1 = np.radians(lat1)
    lon1 = np.radians(lon1)
    lat2 = np.radians(lat2)
    lon2 = np.radians(lon2)

    dlat = lat2 - lat1
    dlon = lon2 - lon1

    a = (
        np.sin(dlat / 2) ** 2
        + np.cos(lat1)
        * np.cos(lat2)
        * np.sin(dlon / 2) ** 2
    )

    c = 2 * np.arcsin(np.sqrt(a))

    return R * c

In [25]:
places_df["distance_km"] = haversine_distance(
    target_lat,
    target_lon,
    places_df["latitude"],
    places_df["longitude"]
)

In [26]:
places_df[
    [
        "name",
        "rating",
        "review_count",
        "price_level",
        "distance_km"
    ]
].sort_values("distance_km")

,name,rating,review_count,price_level,distance_km
19,Glen's Bakehouse Whitefield,4.2,12528,PRICE_LEVEL_MODERATE,0.281532
16,SMOOR Lounge - Whitefield,4.4,1567,NaN,0.452215
1,ChayaChyll,4.7,251,PRICE_LEVEL_MODERATE,1.177127
3,Café Fiori - Dining,4.8,230,PRICE_LEVEL_MODERATE,1.179461
11,The Ants Store and cafe,3.9,644,PRICE_LEVEL_MODERATE,1.217420
13,Bake Stir Fry Cafe,4.6,365,PRICE_LEVEL_MODERATE,1.312602
8,Grill Sip Café,4.8,20,PRICE_LEVEL_INEXPENSIVE,1.712523
9,Lake view cafe,4.7,79,PRICE_LEVEL_INEXPENSIVE,1.715747
18,The Whitefield Cafe,4.6,9,PRICE_LEVEL_INEXPENSIVE,1.850364
2,Paper & Pie,4.3,1153,PRICE_LEVEL_MODERATE,1.958181
17,Third Wave Coffee,4.5,1001,PRICE_LEVEL_MODERATE,1.988700
15,Kink coffee Whitefield,4.5,20,PRICE_LEVEL_MODERATE,2.046970
10,One 9 Popina,4.8,101,PRICE_LEVEL_MODERATE,2.094976
0,Farmhouse Kitchen & Bakery,4.2,1439,PRICE_LEVEL_MODERATE,2.333680
5,Hard Rock Cafe Whitefield,4.5,6183,NaN,2.413640
4,Blue Tokai Coffee Roasters | Divyashree Republ...,4.3,61,PRICE_LEVEL_MODERATE,2.641980
7,Cafe Levista,4.5,93,PRICE_LEVEL_INEXPENSIVE,2.756901
14,Issimo Cafe,4.5,68,PRICE_LEVEL_MODERATE,2.889648
12,Lavonne Café,4.4,316,PRICE_LEVEL_MODERATE,3.256411
6,Beanlore Coffee Roasters - Whitefield,4.3,84,PRICE_LEVEL_EXPENSIVE,4.637913

In [27]:
print(places_df["distance_km"].describe())

count    20.000000
mean      1.995900
std       0.988854
min       0.281532
25%       1.288806
50%       1.973441
75%       2.470725
max       4.637913
Name: distance_km, dtype: float64

In [28]:
nearby_url = "https://places.googleapis.com/v1/places:searchNearby"

nearby_headers = {
    "Content-Type": "application/json",
    "X-Goog-Api-Key": google_maps_key,
    "X-Goog-FieldMask": (
        "places.id,"
        "places.displayName,"
        "places.formattedAddress,"
        "places.rating,"
        "places.userRatingCount,"
        "places.priceLevel,"
        "places.types,"
        "places.location"
    )
}

nearby_payload = {
    "includedTypes": ["cafe"],
    "maxResultCount": 20,
    "locationRestriction": {
        "circle": {
            "center": {
                "latitude": target_lat,
                "longitude": target_lon
            },
            "radius": 3000
        }
    }
}

nearby_response = requests.post(
    nearby_url,
    headers=nearby_headers,
    json=nearby_payload
)

print("Status code:", nearby_response.status_code)
print(nearby_response.text[:2000])

Status code: 200
{
  "places": [
    {
      "id": "ChIJjf6TZDgVrjsRfXPLNj-sbsM",
      "types": [
        "hotel",
        "banquet_hall",
        "vegan_restaurant",
        "vegetarian_restaurant",
        "swimming_pool",
        "massage_spa",
        "spa",
        "cafe",
        "massage",
        "sports_activity_location",
        "event_venue",
        "lodging",
        "service",
        "restaurant",
        "food",
        "point_of_interest",
        "establishment"
      ],
      "formattedAddress": "VYDEHI CIRCLE, ITPL, Vijayanagar, KIADB Export Promotion Industrial Area, Whitefield, Bengaluru, Karnataka 560066, India",
      "location": {
        "latitude": 12.976801799999999,
        "longitude": 77.726541799999993
      },
      "rating": 4.3,
      "userRatingCount": 3869,
      "displayName": {
        "text": "Essotto Recreation Hub",
        "languageCode": "en"
      }
    },
    {
      "id": "ChIJuwVNPf8NrjsR4nDi7CIE0jI",
      "types": [
        "dog_cafe",
        "cafe",
        "pet_boarding_service",
        "pet_care",
        "service",
        "food",
        "point_of_interest",
        "establishment"
      ],
      "formattedAddress": "Therpup Dog Cafe, Kaithota Road, Nagondanahalli Main Rd, Bengaluru, Karnataka 560066, India",
      "location": {
        "latitude": 12.9720265,
        "longitude": 77.7731933
      },
      "rating": 4.3,
      "userRatingCount": 9607,
      "displayName": {
        "text": "Therpup Dog Cafe",
        "languageCode": "en"
      }
    },
    {
      "id": "ChIJuzM6WDkTrjsRduv5wYDLE1I",
      "types": [
        "cafe",
        "food",
        "point_of_interest",
        "establishment"
      ],
      "formattedAddress": "66/2, 2nd Main Rd, Nallurhalli, Whitefield, Bengaluru, Karnataka 560066, India",
      "location": {
        "latitude": 12.965383200000002,
        "longitude": 77.7324064
      },
      "rating": 4.3,
      "priceLevel": "PRICE_LEVEL_MODERATE",
      "userRatingCount": 1153,
      "displayNa

In [29]:
nearby_data = nearby_response.json()

nearby_places = nearby_data.get("places", [])

print("Places returned:", len(nearby_places))

Places returned: 20

In [30]:
nearby_rows = []

for place in nearby_places:
    nearby_rows.append({
        "place_id": place.get("id"),
        "name": place.get("displayName", {}).get("text"),
        "address": place.get("formattedAddress"),
        "rating": place.get("rating"),
        "review_count": place.get("userRatingCount"),
        "price_level": place.get("priceLevel"),
        "types": place.get("types"),
        "latitude": place.get("location", {}).get("latitude"),
        "longitude": place.get("location", {}).get("longitude")
    })

nearby_df = pd.DataFrame(nearby_rows)

print("Shape:", nearby_df.shape)
display(nearby_df)

Shape: (20, 9)

,place_id,name,address,rating,review_count,price_level,types,latitude,longitude
0,ChIJjf6TZDgVrjsRfXPLNj-sbsM,Essotto Recreation Hub,"VYDEHI CIRCLE, ITPL, Vijayanagar, KIADB Export...",4.3,3869,NaN,"[hotel, banquet_hall, vegan_restaurant, vegeta...",12.976802,77.726542
1,ChIJuwVNPf8NrjsR4nDi7CIE0jI,Therpup Dog Cafe,"Therpup Dog Cafe, Kaithota Road, Nagondanahall...",4.3,9607,NaN,"[dog_cafe, cafe, pet_boarding_service, pet_car...",12.972027,77.773193
2,ChIJuzM6WDkTrjsRduv5wYDLE1I,Paper & Pie,"66/2, 2nd Main Rd, Nallurhalli, Whitefield, Be...",4.3,1153,PRICE_LEVEL_MODERATE,"[cafe, food, point_of_interest, establishment]",12.965383,77.732406
3,ChIJX04baGgTrjsRw4WgBajPHwM,Farmhouse Kitchen & Bakery,"Lake View Farm, Main Road, Whitefield Main Rd,...",4.2,1439,PRICE_LEVEL_MODERATE,"[restaurant, garden, parking_lot, parking, cof...",12.956801,77.732992
4,ChIJAwl7EnoRrjsR62wk66pFEH4,Hard Rock Cafe Whitefield,"40, ITPL Main Rd Unit no.G, Ground Floor, 25 &...",4.5,6183,NaN,"[american_restaurant, cafe, pub, bar, restaura...",12.987126,77.736481
5,ChIJaWRA0J0RrjsRETyy6LlVTb4,The Cafe- Lot Like Crepes,"#5 , Avalon, 1st main Road, Whitefield Main Rd...",4.0,1731,PRICE_LEVEL_MODERATE,"[cafe, coffee_shop, breakfast_restaurant, dess...",12.980775,77.750918
6,ChIJ5ZEg0jMTrjsR7MT3Yd2b63c,Third Wave Coffee,"Plot No 207, Varthur Main Rd, Palm Meadows, Ra...",4.5,1001,PRICE_LEVEL_MODERATE,"[cafe, coffee_roastery, coffee_shop, food_stor...",12.957298,77.736776
7,ChIJg0mIojsTrjsRUdVNqM2Z7Bs,Namma Ashram,"126/5/4, Nallurahalli Main Rd, Palm Meadows, S...",4.3,382,NaN,"[cafe, bed_and_breakfast, cultural_center, pri...",12.960249,77.732698
8,ChIJi3s1EQcSrjsR9C0UvfDGXHE,Cafe Palmyra,"Whitefield Main Rd, Phase 1, Ramagondanahalli,...",4.3,1124,NaN,"[restaurant, buffet_restaurant, fine_dining_re...",12.964333,77.739556
9,ChIJyQ9VUhwPrjsRMX-lD-NhAbU,Café Coffee Day,"No. 3/2, 3/5, Ground Flr, 3/3, Whitefield Main...",3.9,1562,PRICE_LEVEL_MODERATE,"[cafe, pastry_shop, sandwich_shop, coffee_shop...",12.979417,77.751318
10,ChIJ1_prIBISrjsRfAQjGMpOlbQ,Starbucks - Whitefield,"Old No 66, 66/1, HAL Old Airport Rd, near Shel...",4.4,2698,PRICE_LEVEL_MODERATE,"[coffee_shop, snack_bar, cafe, meal_takeaway, ...",12.956742,77.732226
11,ChIJm1SCQG0RrjsRwg58a-veTlo,Starbucks - Whitefield,"Unit No G07, GF, International Tech Park Park ...",4.7,1468,PRICE_LEVEL_MODERATE,"[coffee_shop, snack_bar, cafe, meal_takeaway, ...",12.987150,77.736445
12,ChIJWUwXN7kPrjsRz-KGO92MSGg,Leon's Burgers & Wings Whitefield,"205, Swamy Vivekanandha Rd, Prasanth Layout, P...",4.5,2663,PRICE_LEVEL_MODERATE,"[fast_food_restaurant, hamburger_restaurant, c...",12.982636,77.748432
13,ChIJxTQDVAUTrjsRfnR-Q8jVmlI,Bake Stir Fry Cafe,"Shop#2, 56/6, Borewell Rd, near Victorian View...",4.6,365,PRICE_LEVEL_MODERATE,"[cafe, coffee_shop, breakfast_restaurant, food...",12.969021,77.737813
14,ChIJg6tUiTYRrjsRNn6MtmY7pyE,Anchor Ground Floor Cafeteria,"ITPL MLPC 3, ITPL Main Rd, Pattandur Agrahara,...",3.8,24,PRICE_LEVEL_INEXPENSIVE,"[cafe, food, point_of_interest, establishment]",12.984448,77.738356
15,ChIJ0ZpmWPYNrjsRp3x1r1cbEkk,McDonald's,"Unit No 32, Ground Floor, Forum Value Mall, 62...",4.2,1893,PRICE_LEVEL_MODERATE,"[fast_food_restaurant, meal_delivery, food_del...",12.959715,77.747429
16,ChIJowH6Fg0TrjsRj0B4UtprtfE,"Theobroma Bakery and Cake Shop - Miraya Rose, ...","Survey No. 66/1, Hobli, Varthur, Palm Meadows,...",4.0,286,PRICE_LEVEL_MODERATE,"[cake_shop, pastry_shop, dessert_shop, cafe, c...",12.956928,77.732192
17,ChIJs6UNuf4NrjsRGe447V8JLL4,Chef Bakers - Whitefield,"No 580, Silver Square, next to Mayuri Deluxe B...",3.9,399,PRICE_LEVEL_MODERATE,"[bakery, pastry_shop, cake_shop, donut_shop, c...",12.969907,77.749778
18,ChIJA2t-vlMPrjsRmjCRWcdBDmk,Café Fiori - Dining,"B104, Garden of Eden, attandur Agrahara Kalida...",4.8,230,PRICE_LEVEL_MODERATE,"[cafe, dessert_restaurant, coffee_shop, europe...",12.980370,77.750804
19,ChIJIZwdGuURrjsR4I_iUNxFuls,McDonald's,"International Tech Park Park Square Mall, Asce...",4.2,2952,PRICE_LEVEL_MODERATE,"[fast_food_restaurant, meal_delivery, food_del...",12.986972,77.736660

In [31]:
nearby_df["distance_km"] = haversine_distance(
    target_lat,
    target_lon,
    nearby_df["latitude"],
    nearby_df["longitude"]
)

display(
    nearby_df[
        [
            "name",
            "rating",
            "review_count",
            "price_level",
            "distance_km"
        ]
    ].sort_values("distance_km")
)

,name,rating,review_count,price_level,distance_km
17,Chef Bakers - Whitefield,3.9,399,PRICE_LEVEL_MODERATE,0.017794
9,Café Coffee Day,3.9,1562,PRICE_LEVEL_MODERATE,1.080326
15,McDonald's,4.2,1893,PRICE_LEVEL_MODERATE,1.152925
18,Café Fiori - Dining,4.8,230,PRICE_LEVEL_MODERATE,1.179461
5,The Cafe- Lot Like Crepes,4.0,1731,PRICE_LEVEL_MODERATE,1.225340
8,Cafe Palmyra,4.3,1124,NaN,1.275070
13,Bake Stir Fry Cafe,4.6,365,PRICE_LEVEL_MODERATE,1.312602
12,Leon's Burgers & Wings Whitefield,4.5,2663,PRICE_LEVEL_MODERATE,1.436145
2,Paper & Pie,4.3,1153,PRICE_LEVEL_MODERATE,1.958181
6,Third Wave Coffee,4.5,1001,PRICE_LEVEL_MODERATE,1.988700
14,Anchor Ground Floor Cafeteria,3.8,24,PRICE_LEVEL_INEXPENSIVE,2.053617
7,Namma Ashram,4.3,382,NaN,2.145352
3,Farmhouse Kitchen & Bakery,4.2,1439,PRICE_LEVEL_MODERATE,2.333680
19,McDonald's,4.2,2952,PRICE_LEVEL_MODERATE,2.388351
16,"Theobroma Bakery and Cake Shop - Miraya Rose, ...",4.0,286,PRICE_LEVEL_MODERATE,2.393856
10,Starbucks - Whitefield,4.4,2698,PRICE_LEVEL_MODERATE,2.403353
4,Hard Rock Cafe Whitefield,4.5,6183,NaN,2.413640
11,Starbucks - Whitefield,4.7,1468,PRICE_LEVEL_MODERATE,2.418155
1,Therpup Dog Cafe,4.3,9607,NaN,2.536121
0,Essotto Recreation Hub,4.3,3869,NaN,2.648057

In [32]:
print("Duplicate IDs:", nearby_df["place_id"].duplicated().sum())

print("\nMissing values:")
print(nearby_df.isnull().sum())

print("\nDistance statistics:")
print(nearby_df["distance_km"].describe())

Duplicate IDs: 0

Missing values:
place_id        0
name            0
address         0
rating          0
review_count    0
price_level     5
types           0
latitude        0
longitude       0
distance_km     0
dtype: int64

Distance statistics:
count    20.000000
mean      1.818036
std       0.691255
min       0.017794
25%       1.262638
50%       2.021159
75%       2.396231
max       2.648057
Name: distance_km, dtype: float64

 Reusable Nearby Competitor Collector

A reusable function is created to retrieve nearby businesses for a proposed location and business type.

The function:
- queries Google Places Nearby Search
- retrieves relevant place information
- calculates distance from the proposed location
- removes duplicate place IDs
- returns a clean DataFrame

The configured radius is currently 3 km for the prototype.

In [33]:
def get_nearby_competitors(
    latitude,
    longitude,
    business_type,
    radius_km=3,
    max_results=20
):
    url = "https://places.googleapis.com/v1/places:searchNearby"

    headers = {
        "Content-Type": "application/json",
        "X-Goog-Api-Key": google_maps_key,
        "X-Goog-FieldMask": (
            "places.id,"
            "places.displayName,"
            "places.formattedAddress,"
            "places.rating,"
            "places.userRatingCount,"
            "places.priceLevel,"
            "places.types,"
            "places.location"
        )
    }

    payload = {
        "includedTypes": [business_type],
        "maxResultCount": max_results,
        "locationRestriction": {
            "circle": {
                "center": {
                    "latitude": latitude,
                    "longitude": longitude
                },
                "radius": radius_km * 1000
            }
        }
    }

    response = requests.post(
        url,
        headers=headers,
        json=payload
    )

    if response.status_code != 200:
        raise Exception(
            f"Places API error {response.status_code}: "
            f"{response.text}"
        )

    data = response.json()

    rows = []

    for place in data.get("places", []):
        rows.append({
            "place_id": place.get("id"),
            "name": place.get("displayName", {}).get("text"),
            "address": place.get("formattedAddress"),
            "rating": place.get("rating"),
            "review_count": place.get("userRatingCount"),
            "price_level": place.get("priceLevel"),
            "types": place.get("types"),
            "latitude": place.get("location", {}).get("latitude"),
            "longitude": place.get("location", {}).get("longitude")
        })

    df = pd.DataFrame(rows)

    if df.empty:
        return df

    # Remove duplicate businesses
    df = df.drop_duplicates(
        subset="place_id"
    ).reset_index(drop=True)

    # Calculate distance from proposed location
    df["distance_km"] = haversine_distance(
        latitude,
        longitude,
        df["latitude"],
        df["longitude"]
    )

    # Keep only businesses inside requested radius
    df = df[
        df["distance_km"] <= radius_km
    ].copy()

    return df.reset_index(drop=True)

In [34]:
whitefield_cafes = get_nearby_competitors(
    latitude=target_lat,
    longitude=target_lon,
    business_type="cafe",
    radius_km=3,
    max_results=20
)

print("Competitors returned:", len(whitefield_cafes))

display(
    whitefield_cafes[
        [
            "name",
            "rating",
            "review_count",
            "price_level",
            "distance_km"
        ]
    ].sort_values("distance_km")
)

Competitors returned: 20

,name,rating,review_count,price_level,distance_km
17,Chef Bakers - Whitefield,3.9,399,PRICE_LEVEL_MODERATE,0.017794
9,Café Coffee Day,3.9,1562,PRICE_LEVEL_MODERATE,1.080326
15,McDonald's,4.2,1893,PRICE_LEVEL_MODERATE,1.152925
18,Café Fiori - Dining,4.8,230,PRICE_LEVEL_MODERATE,1.179461
5,The Cafe- Lot Like Crepes,4.0,1731,PRICE_LEVEL_MODERATE,1.225340
8,Cafe Palmyra,4.3,1124,NaN,1.275070
13,Bake Stir Fry Cafe,4.6,365,PRICE_LEVEL_MODERATE,1.312602
12,Leon's Burgers & Wings Whitefield,4.5,2663,PRICE_LEVEL_MODERATE,1.436145
2,Paper & Pie,4.3,1153,PRICE_LEVEL_MODERATE,1.958181
6,Third Wave Coffee,4.5,1001,PRICE_LEVEL_MODERATE,1.988700
14,Anchor Ground Floor Cafeteria,3.8,24,PRICE_LEVEL_INEXPENSIVE,2.053617
7,Namma Ashram,4.3,382,NaN,2.145352
3,Farmhouse Kitchen & Bakery,4.2,1439,PRICE_LEVEL_MODERATE,2.333680
19,McDonald's,4.2,2952,PRICE_LEVEL_MODERATE,2.388351
16,"Theobroma Bakery and Cake Shop - Miraya Rose, ...",4.0,286,PRICE_LEVEL_MODERATE,2.393856
10,Starbucks - Whitefield,4.4,2698,PRICE_LEVEL_MODERATE,2.403353
4,Hard Rock Cafe Whitefield,4.5,6183,NaN,2.413640
11,Starbucks - Whitefield,4.7,1468,PRICE_LEVEL_MODERATE,2.418155
1,Therpup Dog Cafe,4.3,9607,NaN,2.536121
0,Essotto Recreation Hub,4.3,3869,NaN,2.648057

In [35]:
print("Duplicate IDs:",
      whitefield_cafes["place_id"].duplicated().sum())

print("\nMissing values:")
print(whitefield_cafes.isnull().sum())

print("\nDistance:")
print(whitefield_cafes["distance_km"].describe())

Duplicate IDs: 0

Missing values:
place_id        0
name            0
address         0
rating          0
review_count    0
price_level     5
types           0
latitude        0
longitude       0
distance_km     0
dtype: int64

Distance:
count    20.000000
mean      1.818036
std       0.691255
min       0.017794
25%       1.262638
50%       2.021159
75%       2.396231
max       2.648057
Name: distance_km, dtype: float64

In [36]:
competition_summary = {
    "competitor_count_retrieved": len(whitefield_cafes),
    "avg_competitor_rating": whitefield_cafes["rating"].mean(),
    "median_competitor_rating": whitefield_cafes["rating"].median(),
    "avg_competitor_reviews": whitefield_cafes["review_count"].mean(),
    "median_competitor_reviews": whitefield_cafes["review_count"].median(),
    "high_rating_competitors": (
        whitefield_cafes["rating"] >= 4.5
    ).sum(),
    "high_review_competitors": (
        whitefield_cafes["review_count"] >= 1000
    ).sum()
}

competition_summary

{'competitor_count_retrieved': 20,
 'avg_competitor_rating': np.float64(4.285000000000001),
 'median_competitor_rating': np.float64(4.3),
 'avg_competitor_reviews': np.float64(2051.45),
 'median_competitor_reviews': np.float64(1453.5),
 'high_rating_competitors': np.int64(6),
 'high_review_competitors': np.int64(14)}

In [37]:
import os

os.makedirs("../data/raw/places", exist_ok=True)

In [38]:
whitefield_cafes.to_csv(
    "../data/raw/places/whitefield_cafes.csv",
    index=False
)

print("Saved successfully.")

Saved successfully.

In [39]:
print(
    os.path.exists(
        "../data/raw/places/whitefield_cafes.csv"
    )
)

True

In [40]:
whitefield_restaurants = get_nearby_competitors(
    latitude=target_lat,
    longitude=target_lon,
    business_type="restaurant",
    radius_km=3,
    max_results=20
)

print(
    "Restaurant competitors retrieved:",
    len(whitefield_restaurants)
)

Restaurant competitors retrieved: 20

In [41]:
display(
    whitefield_restaurants[
        [
            "name",
            "rating",
            "review_count",
            "distance_km"
        ]
    ].sort_values("distance_km")
)

,name,rating,review_count,distance_km
2,Anand Sweets - Whitefield,4.3,9355,0.196518
4,Glen's Bakehouse Whitefield,4.2,12528,0.281532
3,"Lemon Tree Suites ,Whitefield, Bengaluru",4.2,720,0.385678
11,Kake Di Hatti Whitefield,4.5,3982,0.450978
8,153 Biere Street | Best Microbrewery in Whitef...,4.2,2451,0.733072
9,Oakwood Residence Whitefield Bangalore,4.6,1924,1.140154
14,Telugu Aromas - Whitefields,4.0,1557,1.509023
12,Adyar Ananda Bhavan - A2B,4.2,20021,1.549276
5,Dhaba Square,4.5,6985,1.582408
17,South Socials,3.9,2793,2.013993
0,URU (Kaavu) - Whitefield,4.3,3610,2.109902
15,Farmhouse Kitchen & Bakery,4.2,1439,2.333680
16,Hard Rock Cafe Whitefield,4.5,6183,2.413640
7,Essotto Recreation Hub,4.3,3869,2.648057
1,The Den Bengaluru,4.5,11100,2.678320
19,LITBOX,4.3,708,2.680069
13,Chez Mariannick Bakery Restaurant,4.1,1609,2.729991
18,Babai Hotel - Since 1942,3.9,1029,2.811399
10,"AB's - Absolute Barbecues | Whitefield, Bangalore",4.2,17451,2.824357
6,ASF - Ancient Stone Flames BBQ & Grill,4.6,4746,2.970838

In [42]:
from collections import Counter

all_types = []

for types_list in whitefield_restaurants["types"]:
    all_types.extend(types_list)

type_counts = Counter(all_types)

type_counts.most_common(30)

[('restaurant', 20),
 ('food', 20),
 ('point_of_interest', 20),
 ('establishment', 20),
 ('food_store', 6),
 ('store', 6),
 ('service', 6),
 ('indian_restaurant', 6),
 ('bar', 5),
 ('hotel', 4),
 ('banquet_hall', 4),
 ('bakery', 4),
 ('lodging', 4),
 ('event_venue', 4),
 ('breakfast_restaurant', 3),
 ('pizza_restaurant', 3),
 ('cafe', 3),
 ('south_indian_restaurant', 3),
 ('spa', 2),
 ('fast_food_restaurant', 2),
 ('confectionery', 2),
 ('north_indian_restaurant', 2),
 ('fine_dining_restaurant', 2),
 ('chinese_restaurant', 2),
 ('buffet_restaurant', 2),
 ('vegetarian_restaurant', 2),
 ('pub', 2),
 ('mediterranean_restaurant', 1),
 ('business_center', 1),
 ('cottage', 1)]

In [43]:
import joblib

rf_model = joblib.load("../models/zomato_performance_model.pkl")
preprocessor = joblib.load("../models/zomato_preprocessor.pkl")

print("Model loaded:", type(rf_model).__name__)
print("Preprocessor loaded:", type(preprocessor).__name__)

Model loaded: RandomForestClassifier
Preprocessor loaded: ColumnTransformer

In [44]:
print("Classes:", rf_model.classes_)

Classes: ['High' 'Low' 'Medium']

In [47]:
print(preprocessor.feature_names_in_)

['online_order' 'book_table' 'approx_costfor_two_people' 'log_cost'
 'cost_band' 'location' 'primary_cuisine' 'cuisine_count'
 'primary_rest_type' 'historical_restaurant_count' 'location_median_cost'
 'location_online_order_rate' 'location_book_table_rate'
 'location_cuisine_diversity' 'location_business_type_diversity']

In [48]:
print("Number of input features:", len(preprocessor.feature_names_in_))

Number of input features: 15

In [49]:
test_business = pd.DataFrame([{
    "online_order": 1,
    "book_table": 0,
    "approx_costfor_two_people": 500,
    "log_cost": np.log1p(500),
    "cost_band": "Mid-Range",
    "location": "Whitefield",
    "primary_cuisine": "Cafe",
    "cuisine_count": 3,
    "primary_rest_type": "Cafe",
    "historical_restaurant_count": 1231,
    "location_median_cost": 400,
    "location_online_order_rate": 0.70,
    "location_book_table_rate": 0.10,
    "location_cuisine_diversity": 40,
    "location_business_type_diversity": 15
}])

display(test_business)

,online_order,book_table,approx_costfor_two_people,log_cost,cost_band,location,primary_cuisine,cuisine_count,primary_rest_type,historical_restaurant_count,location_median_cost,location_online_order_rate,location_book_table_rate,location_cuisine_diversity,location_business_type_diversity
0,1,0,500,6.216606,Mid-Range,Whitefield,Cafe,3,Cafe,1231,400,0.7,0.1,40,15

In [50]:
test_business_encoded = preprocessor.transform(test_business)

print("Encoded shape:", test_business_encoded.shape)

Encoded shape: (1, 219)

In [51]:
prediction = rf_model.predict(test_business_encoded)

probabilities = rf_model.predict_proba(
    test_business_encoded
)

print("Prediction:", prediction[0])

print("\nProbabilities:")

for class_name, probability in zip(
    rf_model.classes_,
    probabilities[0]
):
    print(f"{class_name}: {probability:.3f}")

Prediction: Low

Probabilities:
High: 0.295
Low: 0.436
Medium: 0.270

In [52]:
print("=== HISTORICAL MODEL ===")

for class_name, probability in zip(
    rf_model.classes_,
    probabilities[0]
):
    print(f"{class_name}: {probability:.3f}")

print("\n=== CURRENT COMPETITION ===")

for key, value in competition_summary.items():
    print(f"{key}: {value}")

=== HISTORICAL MODEL ===
High: 0.295
Low: 0.436
Medium: 0.270

=== CURRENT COMPETITION ===
competitor_count_retrieved: 20
avg_competitor_rating: 4.285000000000001
median_competitor_rating: 4.3
avg_competitor_reviews: 2051.45
median_competitor_reviews: 1453.5
high_rating_competitors: 6
high_review_competitors: 14

In [53]:
competition_score = (
    (competition_summary["avg_competitor_rating"] / 5) * 40
    +
    min(
        competition_summary["avg_competitor_reviews"] / 2000,
        1
    ) * 30
    +
    (
        competition_summary["high_rating_competitors"]
        / competition_summary["competitor_count_retrieved"]
    ) * 15
    +
    (
        competition_summary["high_review_competitors"]
        / competition_summary["competitor_count_retrieved"]
    ) * 15
)

print("Competition strength score:",
      round(competition_score, 2))

Competition strength score: 79.28

In [54]:
performance_score = (
    probabilities[0][list(rf_model.classes_).index("High")] * 100
    +
    probabilities[0][list(rf_model.classes_).index("Medium")] * 50
)

opportunity_score = (
    0.60 * performance_score
    +
    0.40 * (100 - competition_score)
)

print("Performance score:",
      round(performance_score, 2))

print("Competition strength:",
      round(competition_score, 2))

print("Opportunity score:",
      round(opportunity_score, 2))

Performance score: 42.97
Competition strength: 79.28
Opportunity score: 34.07

In [55]:
recommendation_factors = {
    "historical_performance": performance_score,
    "competition_strength": competition_score,
    "competition_opportunity": 100 - competition_score
}

print("Recommendation factors:")
for key, value in recommendation_factors.items():
    print(f"{key}: {value:.2f}")

Recommendation factors:
historical_performance: 42.97
competition_strength: 79.28
competition_opportunity: 20.72

In [56]:
if performance_score < 40:
    performance_signal = "Weak historical performance"
elif performance_score < 60:
    performance_signal = "Moderate historical performance"
else:
    performance_signal = "Strong historical performance"

if competition_score >= 70:
    competition_signal = "Strong competition"
elif competition_score >= 40:
    competition_signal = "Moderate competition"
else:
    competition_signal = "Limited competition"

print("Performance signal:", performance_signal)
print("Competition signal:", competition_signal)

Performance signal: Moderate historical performance
Competition signal: Strong competition

In [57]:
if opportunity_score < 40:
    opportunity_class = "Low"
elif opportunity_score < 70:
    opportunity_class = "Moderate"
else:
    opportunity_class = "High"

print("Opportunity class:", opportunity_class)

Opportunity class: Low

In [58]:
recommendation = {
    "opportunity_score": round(opportunity_score, 2),
    "opportunity_class": opportunity_class,
    "historical_performance": round(performance_score, 2),
    "competition_strength": round(competition_score, 2),
    "performance_signal": performance_signal,
    "competition_signal": competition_signal
}

recommendation

{'opportunity_score': np.float64(34.07),
 'opportunity_class': 'Low',
 'historical_performance': np.float64(42.97),
 'competition_strength': np.float64(79.28),
 'performance_signal': 'Moderate historical performance',
 'competition_signal': 'Strong competition'}

In [59]:
def analyze_business_opportunity(
    probabilities,
    model_classes,
    competition_summary
):
    """
    Combine historical ML performance and current competition
    into a rule-based business opportunity assessment.
    """

    # -----------------------------
    # 1. Historical performance
    # -----------------------------
    
    class_probabilities = dict(
        zip(model_classes, probabilities)
    )

    high_probability = class_probabilities.get("High", 0)
    medium_probability = class_probabilities.get("Medium", 0)

    performance_score = (
        high_probability * 100
        + medium_probability * 50
    )

    # -----------------------------
    # 2. Competition strength
    # -----------------------------

    competitor_count = competition_summary[
        "competitor_count_retrieved"
    ]

    avg_rating = competition_summary[
        "avg_competitor_rating"
    ]

    avg_reviews = competition_summary[
        "avg_competitor_reviews"
    ]

    high_rating_count = competition_summary[
        "high_rating_competitors"
    ]

    high_review_count = competition_summary[
        "high_review_competitors"
    ]

    # Avoid division by zero
    if competitor_count > 0:

        competition_score = (
            (avg_rating / 5) * 40
            +
            min(avg_reviews / 2000, 1) * 30
            +
            (high_rating_count / competitor_count) * 15
            +
            (high_review_count / competitor_count) * 15
        )

    else:
        competition_score = 0

    # -----------------------------
    # 3. Opportunity score
    # -----------------------------

    opportunity_score = (
        0.60 * performance_score
        +
        0.40 * (100 - competition_score)
    )

    # -----------------------------
    # 4. Signals
    # -----------------------------

    if performance_score < 40:
        performance_signal = "Weak historical performance"
    elif performance_score < 60:
        performance_signal = "Moderate historical performance"
    else:
        performance_signal = "Strong historical performance"

    if competition_score >= 70:
        competition_signal = "Strong competition"
    elif competition_score >= 40:
        competition_signal = "Moderate competition"
    else:
        competition_signal = "Limited competition"

    # -----------------------------
    # 5. Opportunity classification
    # -----------------------------

    if opportunity_score < 40:
        opportunity_class = "Low"
    elif opportunity_score < 70:
        opportunity_class = "Moderate"
    else:
        opportunity_class = "High"

    # -----------------------------
    # 6. Final structured output
    # -----------------------------

    return {
        "opportunity_score": round(
            float(opportunity_score), 2
        ),
        "opportunity_class": opportunity_class,

        "historical_performance": round(
            float(performance_score), 2
        ),

        "competition_strength": round(
            float(competition_score), 2
        ),

        "performance_signal": performance_signal,
        "competition_signal": competition_signal
    }

In [60]:
recommendation = analyze_business_opportunity(
    probabilities=probabilities[0],
    model_classes=rf_model.classes_,
    competition_summary=competition_summary
)

recommendation

{'opportunity_score': 34.07,
 'opportunity_class': 'Low',
 'historical_performance': 42.97,
 'competition_strength': 79.28,
 'performance_signal': 'Moderate historical performance',
 'competition_signal': 'Strong competition'}

In [61]:
print("Previous opportunity score:", 34.07)
print(
    "Function opportunity score:",
    recommendation["opportunity_score"]
)

print(
    "Previous class: Low"
)

print(
    "Function class:",
    recommendation["opportunity_class"]
)

Previous opportunity score: 34.07
Function opportunity score: 34.07
Previous class: Low
Function class: Low